title: Haodong Cui's Homepage
url: 'https://haodongcui.github.io'
baseurl: ''
author:
  name: Haodong Cui
  email: cuihd2004@163.com

# 添加图片路径配置
include:
  - images

# static_files:
#   - assets/images/
#   - assets/js/
#   - assets/css/
