title: Haodong Cui's Homepage
url: "https://haodongcui.github.io"
baseurl: ""
author:
  name: Haodong Cui
  email: cuihd2004@163.com

# static_files:
#   - assets/images/
#   - assets/js/
#   - assets/css/
